### ISSUE TITLE
TODO: Port wiki docs over

### ISSUE THREAD

**Issue by jerdog** [omnirom/Docs#1]
- [x] https://docs.omnirom.org/Code_of_Conduct
- [x] lowest section of https://docs.omnirom.org/Porting_Omni_To_Your_Device ONLY
- [x] https://docs.omnirom.org/Using_repo_and_git
- [x] https://docs.omnirom.org/Gerrit_Rules
- [x] https://docs.omnirom.org/Omni_Contributor_License_Agreement
- [x] https://docs.omnirom.org/Contributing_code
- [ ] https://docs.omnirom.org/Setting_Up_A_Compile_Environment 
- [ ] https://docs.omnirom.org/Build_for_i9300 (most comprehensive one)
- [ ] https://docs.omnirom.org/Device_overlays [ issue #2 ]

**Comment by jerdog** [comment]
- Code of Conduct already ported
- Porting to your device done

**Comment by jerdog** [comment]
CLA ported over to Omni Community repo and linked in Docs README

**Comment by eNTi** [comment]
I'm new to this and would like to start by building for my maguro (tuna). It's really quite confusing finding the right documentation at the moment, if there even is such a thing. Any chance you could finish the transition from the wiki to github or update the wiki to a working state?
